# NumPy


In [1]:
import numpy as np

In [2]:
np.arange(5) ##simple array##

array([0, 1, 2, 3, 4])

In [3]:
arr=np.arange(0,50).reshape(5,10) ##converting array into 5 rows and 10 cols##

In [4]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [5]:
arr[1:3,3:5]   ##Accessing array using slicing##

array([[13, 14],
       [23, 24]])

import numpy as np
row=int(input("Enter no. of rows"))
col=int(input("Enter no. of columns"))
for i in range(row,col):
    input()
np.arange(row,col)

In [6]:
import numpy as np

In [7]:
##user defined array##
import numpy as np
row=int(input("Enter no. of rows "))
col=int(input("Enter no. of columns "))
a=np.zeros((row,col),dtype=int)
print("Enter elements of array ")
for i in range(row):
    for j in range(col):
        a[i][j]=int(input())  ##Take input from user to make a array ##
        ##NOTE :- enter element by pressing "Enter" after giving every input##
print(a)
if(5 in a): ##checking if an element is present in Array or not ##
    print("found")
else:
    print("not found")

Enter no. of rows 3
Enter no. of columns 4
Enter elements of array 
12
22
34
11
67
88
6
32
100
23
90
17
[[ 12  22  34  11]
 [ 67  88   6  32]
 [100  23  90  17]]
not found


In [8]:
##Sum of user defined array ##
import numpy as np
m,n=[int (x) for x in input("Enter no. of rows and column of 1st array ").split()]
m1,n1=[int (x) for x in input("Enter no. of rows and column of 2nd array ").split()]
arr1=np.zeros((m,n),dtype=int)
arr2=np.zeros((m1,n1),dtype=int)
print("Enter elements of 1st array ")
for i in range(m):
    for j in range(n):
        arr1[i][j]=int(input())
print("Enter elements of second array ")
for k in range(m1):
    for l in range(n1):
        arr2[k][l]=int(input())
print("First array : ")
print(arr1)
print("Second array : ")
print(arr2)
print("Their sum is ")
print(arr1+arr2)

Enter no. of rows and column of 1st array 2 3
Enter no. of rows and column of 2nd array 2 3
Enter elements of 1st array 
12
34
56
78
11
23
Enter elements of second array 
34
11
65
88
89
12
First array : 
[[12 34 56]
 [78 11 23]]
Second array : 
[[34 11 65]
 [88 89 12]]
Their sum is 
[[ 46  45 121]
 [166 100  35]]


# pandas

In [9]:
import pandas as pd
import numpy as np

In [10]:
labels=['A','B','C']
my_data=[10,20,30]

In [11]:
ser1=pd.Series(my_data,labels) ## making series ##
ser1

A    10
B    20
C    30
dtype: int64

In [12]:
ser1[1]

20

In [13]:
from numpy.random import randn

In [14]:
data_fram=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z']) ## making frames##
data_fram

W         X         Y         Z
A  1.153832  0.944006  1.785927 -0.487917
B  0.705143  0.105979 -1.926956 -0.933115
C  1.075279 -0.139452 -1.096689 -1.821004
D  0.487028  0.548946 -1.740210 -0.067371
E  0.222930  0.170160  1.597474  0.462714

In [15]:
data_fram['W']

A    1.153832
B    0.705143
C    1.075279
D    0.487028
E    0.222930
Name: W, dtype: float64

In [16]:
data_fram[['W','X']] ##accessing Columns of DataFrames using slicing##

W         X
A  1.153832  0.944006
B  0.705143  0.105979
C  1.075279 -0.139452
D  0.487028  0.548946
E  0.222930  0.170160

In [17]:
newcol=data_fram['W']+data_fram['X']
newcol

A    2.097838
B    0.811122
C    0.935828
D    1.035974
E    0.393090
dtype: float64

In [18]:
data_fram.loc['A']

W    1.153832
X    0.944006
Y    1.785927
Z   -0.487917
Name: A, dtype: float64

In [19]:
data_fram

W         X         Y         Z
A  1.153832  0.944006  1.785927 -0.487917
B  0.705143  0.105979 -1.926956 -0.933115
C  1.075279 -0.139452 -1.096689 -1.821004
D  0.487028  0.548946 -1.740210 -0.067371
E  0.222930  0.170160  1.597474  0.462714

In [20]:
data_fram>0

W      X      Y      Z
A  True   True   True  False
B  True   True  False  False
C  True  False  False  False
D  True   True  False  False
E  True   True   True   True

In [21]:
boolans=data_fram[data_fram['W']>0]
print(boolans)

          W         X         Y         Z
A  1.153832  0.944006  1.785927 -0.487917
B  0.705143  0.105979 -1.926956 -0.933115
C  1.075279 -0.139452 -1.096689 -1.821004
D  0.487028  0.548946 -1.740210 -0.067371
E  0.222930  0.170160  1.597474  0.462714


In [22]:
data_fram[data_fram['W']>0][['Y','X']]

Y         X
A  1.785927  0.944006
B -1.926956  0.105979
C -1.096689 -0.139452
D -1.740210  0.548946
E  1.597474  0.170160

In [23]:
data_fram.reset_index()

index         W         X         Y         Z
0     A  1.153832  0.944006  1.785927 -0.487917
1     B  0.705143  0.105979 -1.926956 -0.933115
2     C  1.075279 -0.139452 -1.096689 -1.821004
3     D  0.487028  0.548946 -1.740210 -0.067371
4     E  0.222930  0.170160  1.597474  0.462714

In [24]:
newc='DE,MU,BI,NA,RA'.split()
newc

['DE,MU,BI,NA,RA']

In [25]:
#data_fram['T']=newc
#data_fram.set_index('T',inplace=True)

In [26]:
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)  ##make outer Index(g1,g2) and inner index (S,V)##
data_fram=pd.DataFrame(randn(6,2),hier_index,['S','V'])
data_fram

S         V
G1 1 -1.162604  0.933877
   2  0.617575 -0.658026
   3 -1.702448  0.229735
G2 1 -0.412159 -1.726556
   2  0.902216  1.960175
   3 -0.711887  1.937194

In [27]:
data_fram.loc['G1'].loc[1] ##accessing rows using slicing ##

S   -1.162604
V    0.933877
Name: 1, dtype: float64

In [28]:
data_fram.xs('G1')

S         V
1 -1.162604  0.933877
2  0.617575 -0.658026
3 -1.702448  0.229735